/**
 * Agent 编排节点面板配置（n8n 风格分类）
 */

import type { AgentNodeType } from '@/types/agentWorkflow'
import { EXPERT_NODE_TYPE_META } from '@/constants/expertNodeTypes'

export interface AgentPaletteItem {
  type: AgentNodeType
  label: string
  icon: string
  category: 'trigger' | 'ai' | 'experts' | 'logic' | 'tools' | 'action'
  description: string
  defaultData: Partial<import('@/types/agentWorkflow').AgentWorkflowNodeData>
}

export const AGENT_PALETTE_ITEMS: AgentPaletteItem[] = [
  {
    type: 'manual-trigger',
    label: '手动触发',
    icon: 'video-play',
    category: 'trigger',
    description: '设计器测试或内部 API 手动启动（入口节点）',
    defaultData: { label: '手动触发' },
  },
  {
    type: 'webhook-trigger',
    label: 'Webhook 触发',
    icon: 'bell',
    category: 'trigger',
    description: '外部 HTTP 调用 Webhook 地址时从此入口进入',
    defaultData: { label: 'Webhook 触发', webhookPath: '/hook', webhookMethod: 'POST' },
  },
  {
    type: 'schedule-trigger',
    label: '定时触发',
    icon: 'alarm-clock',
    category: 'trigger',
    description: '按 cron 表达式定时启动（发布后生效，每分钟检查）',
    defaultData: { label: '定时触发', scheduleCron: '0 9 * * *', scheduleTimezone: 'Asia/Shanghai', scheduleEnabled: true },
  },
  {
    type: 'agent-team',
    label: '智能团队',
    icon: 'user',
    category: 'ai',
    description: '多智能体协作：主管调度团队成员（各自人设/模型/工具），讨论或顺序完成任务',
    defaultData: {
      label: '智能团队',
      agentTeamMembers: [
        { name: '产品', persona: '产品经理，负责需求分析和方案设计', tools: [] },
        { name: '开发', persona: '开发工程师，负责技术实现和代码编写', tools: [] },
      ],
      agentTeamMode: 'sequential',
      agentTeamMaxRounds: 5,
      agentTeamModel: 'default',
      agentTeamSystemPrompt: '',
      agentLoopMaxToolInvocations: 50,
    },
  },
  {
    type: 'document-parse',
    label: '文档解析',
    icon: 'document',
    category: 'ai',
    description: '解析已上传文档，输出全文与分块',
    defaultData: {
      label: '文档解析',
      documentSource: 'stream',
      streamField: 'file',
    },
  },
  {
    type: 'vision-analyze',
    label: '图片视觉分析',
    icon: 'picture',
    category: 'ai',
    description: '对已上传图片做纯视觉语义描述（非 OCR）',
    defaultData: {
      label: '图片视觉分析',
      documentSource: 'stream',
      streamField: 'file',
      visionPrompt: '',
    },
  },
  {
    type: 'audio-transcribe',
    label: '音频转录',
    icon: 'microphone',
    category: 'ai',
    description: '使用 Whisper 将音频文件转录为文字',
    defaultData: {
      label: '音频转录',
      documentSource: 'stream',
      streamField: 'file',
      language: 'zh',
    },
  },
  {
    type: 'video-analyze',
    label: '视频分析',
    icon: 'video-camera',
    category: 'ai',
    description: '提取视频关键帧并使用视觉模型分析内容',
    defaultData: {
      label: '视频分析',
      documentSource: 'stream',
      streamField: 'file',
      visionPrompt: '',
      maxFrames: 10,
    },
  },
  {
    type: 'conversation-memory',
    label: '对话记忆',
    icon: 'chat-dot-round',
    category: 'logic',
    description: '读取/追加/重置多轮对话历史',
    defaultData: {
      label: '对话记忆',
      memoryMode: 'append',
      memoryRole: 'user',
      messageField: 'message',
      maxHistoryTurns: 20,
    },
  },
  {
    type: 'memory-recall',
    label: '长程记忆检索',
    icon: 'search',
    category: 'logic',
    description: '从用户长程记忆库检索跨会话记忆，注入下游 prompt',
    defaultData: {
      label: '长程记忆检索',
      memoryRecallQuery: '{{$input.message}}',
      memoryRecallLimit: 5,
      memoryRecallNamespace: 'all',
      memoryRecallUserIdSource: 'auto',
    },
  },
  {
    type: 'memory-write',
    label: '长程记忆写入',
    icon: 'edit',
    category: 'logic',
    description: '将一条记忆持久化到用户长程记忆库（跨会话可召回）',
    defaultData: {
      label: '长程记忆写入',
      memoryWriteContent: '{{$input.message}}',
      memoryWriteNamespace: 'fact',
      memoryWriteImportance: 0.5,
      memoryWriteUserIdSource: 'auto',
    },
  },
  {
    type: 'memory-extract',
    label: '长程记忆提取',
    icon: 'magic-stick',
    category: 'ai',
    description: 'LLM 从对话/节点输出提取值得记忆的事实/偏好，输出可接记忆写入',
    defaultData: {
      label: '长程记忆提取',
      memoryExtractSource: 'lastOutput',
      memoryExtractModel: 'default',
      memoryExtractNamespace: 'fact',
    },
  },
  {
    type: 'handoff',
    label: '会话交接',
    icon: 'switch',
    category: 'logic',
    description: '将会话控制权转移给目标已发布 workflow（传递对话历史，目标 persona 接管）',
    defaultData: {
      label: '会话交接',
      handoffTargetWorkflowId: '',
      handoffPassHistory: true,
      handoffInputTemplate: '{{$input.message}}',
    },
  },
  {
    type: 'llm',
    label: 'LLM',
    icon: 'cpu',
    category: 'ai',
    description: '调用大模型处理文本',
    defaultData: { label: 'LLM', prompt: '{{$input.message}}', model: 'default' },
  },
  {
    type: 'agent-intent',
    label: EXPERT_NODE_TYPE_META['agent-intent'].label,
    icon: EXPERT_NODE_TYPE_META['agent-intent'].icon,
    category: 'experts',
    description: EXPERT_NODE_TYPE_META['agent-intent'].description,
    defaultData: { label: EXPERT_NODE_TYPE_META['agent-intent'].label },
  },
  {
    type: 'if',
    label: '条件分支',
    icon: 'share',
    category: 'logic',
    description: '按表达式选择分支',
    defaultData: { label: 'IF', expression: 'lastOutput' },
  },
  {
    type: 'merge',
    label: '合流',
    icon: 'connection',
    category: 'logic',
    description: '等待多路上游完成后合并上下文',
    defaultData: { label: '合流', mergeWait: 'all', mergeTextTemplate: '' },
  },
  {
    type: 'hitl',
    label: '人工确认',
    icon: 'bell',
    category: 'logic',
    description: '暂停等待人工输入',
    defaultData: {
      label: '人工确认',
      confirmMessage: '请确认是否继续',
      confirmQuestions: [],
      inheritUpstreamQuestions: true,
    },
  },
  {
    type: 'tool',
    label: '工具',
    icon: 'setting',
    category: 'tools',
    description: '在属性面板中选择具体工具（不再平铺全部工具）',
    defaultData: { label: '工具' },
  },
  {
    type: 'expert',
    label: '专家',
    icon: 'user',
    category: 'experts',
    description: '在属性面板中选择注册专家',
    defaultData: { label: '专家' },
  },
  {
    type: 'end',
    label: '结束',
    icon: 'circle-check',
    category: 'action',
    description: '结束工作流',
    defaultData: { label: '结束' },
  },
  {
    type: 'image-generate',
    label: '图片生成',
    icon: 'picture',
    category: 'ai',
    description: '调用 AI 生成图片（DALL-E 3 / Mimo 等）',
    defaultData: {
      label: '图片生成',
      imagePrompt: '{{$input.message}}',
      imageModel: '',
      imageSize: '1024x1024',
      imageStyle: 'vivid',
      imageQuality: 'standard',
      imageCount: 1,
    },
  },
  {
    type: 'video-generate',
    label: '视频生成',
    icon: 'video-play',
    category: 'ai',
    description: '调用 AI 生成短视频（6-15s），节点内置轮询直到完成',
    defaultData: {
      label: '视频生成',
      videoPrompt: '{{$input.message}}',
      videoModel: '',
      duration: 8,
      resolution: '720p',
      pollIntervalMs: 5000,
      pollTimeoutMs: 300000,
    },
  },
  {
    type: 'ppt-generate',
    label: 'PPT 生成',
    icon: 'data-board',
    category: 'ai',
    description: '根据文本内容自动生成演示文稿',
    defaultData: {
      label: 'PPT 生成',
      pptTemplate: 'business',
      pptMaxSlides: 10,
      pptStyle: 'professional',
      pptIncludeImages: false,
    },
  },
  {
    type: 'intent-router',
    label: '意图路由',
    icon: 'share',
    category: 'logic',
    description: '自动识别用户意图并路由到对应专家',
    defaultData: {
      label: '意图路由',
      routingMode: 'auto',
      enableMultiIntentChain: false,
      fallbackExpertId: '',
    },
  },
  {
    type: 'summarizer',
    label: '多步总结',
    icon: 'document',
    category: 'ai',
    description: '汇总任务链输出或自定义内容生成摘要',
    defaultData: {
      label: '多步总结',
      summarySource: 'taskChain',
      customPrompt: '',
      stream: false,
      model: 'default',
    },
  },
  {
    type: 'requirement-analyzer',
    label: '需求分析',
    icon: 'search',
    category: 'ai',
    description: '分析用户需求的完整性与可行性',
    defaultData: {
      label: '需求分析',
      enableRag: true,
      enableTools: true,
      completenessThreshold: 80,
      model: 'default',
    },
  },
  {
    type: 'task-planner',
    label: '任务规划',
    icon: 'list',
    category: 'ai',
    description: '将需求拆解为可执行的任务步骤',
    defaultData: {
      label: '任务规划',
      inputSource: 'message',
      maxSteps: 8,
      strategy: 'sequential',
      model: 'default',
    },
  },
  {
    type: 'task-chain',
    label: '任务链',
    icon: 'connection',
    category: 'logic',
    description: '按步骤依次执行任务链中的每个任务',
    defaultData: {
      label: '任务链',
      chainSource: 'upstream',
      staticChain: [],
      onStepOutput: '',
    },
  },
  {
    type: 'collaboration-router',
    label: '协作路由',
    icon: 'coordinate',
    category: 'logic',
    description: '检测协作工具并路由多轮协作交互',
    defaultData: {
      label: '协作路由',
      detectCollaborationTool: true,
      maxCollaborationRounds: 3,
    },
  },
  {
    type: 'agent-loop',
    label: '智能体循环',
    icon: 'magic-stick',
    category: 'ai',
    description: 'LLM 自主循环调用工具，让工作流段落具备智能体能力',
    defaultData: {
      label: '智能体循环',
      model: 'default',
      agentLoopTools: [],
      agentLoopMaxIterations: 8,
      agentLoopSystemPrompt: '你是一个自主智能体，根据用户请求调用可用工具完成任务。每次思考后选择一个工具调用，获得结果后继续，直到任务完成时直接给出最终回答（不要调用工具）。',
      agentLoopInputSource: 'message',
      agentLoopInputTemplate: '',
    },
  },
  {
    type: 'code-execute',
    label: '代码执行',
    icon: 'document',
    category: 'tools',
    description: '在沙箱中执行 JavaScript 代码，支持 $input 和 $node 变量',
    defaultData: {
      label: '代码执行',
      codeLanguage: 'javascript',
      codeScript: '// 可用变量：$input（工作流输入）、$node（上游节点输出）\n// 返回值作为节点输出\nreturn { result: $input.message }',
    },
  },
  {
    type: 'variable-set',
    label: '变量赋值',
    icon: 'edit',
    category: 'tools',
    description: '设置或更新工作流变量，支持 set/append/increment 模式',
    defaultData: {
      label: '变量赋值',
      variableName: 'myVar',
      variableValue: '{{$input.message}}',
      variableMode: 'set',
    },
  },
  {
    type: 'switch',
    label: '多路分支',
    icon: 'sort',
    category: 'logic',
    description: '根据多个条件表达式路由到不同分支，类似 switch-case',
    defaultData: {
      label: '多路分支',
      switchBranches: [
        { label: '分支A', expression: 'true' },
        { label: '分支B', expression: 'false' },
      ],
    },
  },
  {
    type: 'approval-analyze',
    label: '审批建议',
    icon: 'circle-check',
    category: 'ai',
    description: '分析表单审批提交内容，结合上下文给出审批建议',
    defaultData: {
      label: '审批建议',
      approvalSubmissionSource: 'input',
      approvalModel: 'default',
    },
  },
  {
    type: 'flow-interact',
    label: '流程交互',
    icon: 'connection',
    category: 'ai',
    description: '与流程引擎交互：发起流程、查询状态、审批/驳回',
    defaultData: {
      label: '流程交互',
      flowInteractAction: 'query',
    },
  },
  {
    type: 'compliance-check',
    label: '合规检查',
    icon: 'warning-filled',
    category: 'ai',
    description: '按行业合规规则检查内容合规性，输出违规项与建议',
    defaultData: {
      label: '合规检查',
      complianceIndustry: 'general',
      complianceRules: [],
    },
  },
  {
    type: 'module-assemble',
    label: '模块组装',
    icon: 'grid',
    category: 'ai',
    description: '按业务模块类型（OA/HR/财务/审计）组装方案或页面结构',
    defaultData: {
      label: '模块组装',
      moduleType: 'custom',
    },
  },
  {
    type: 'form-query',
    label: '表单查询',
    icon: 'search',
    category: 'ai',
    description: '按表单 ID 和过滤条件查询表单数据，支持数量限制',
    defaultData: {
      label: '表单查询',
      formQueryLimit: 10,
    },
  },
  {
    type: 'anomaly-detect',
    label: '异常检测',
    icon: 'data-analysis',
    category: 'ai',
    description: '按指定维度检测数据异常，输出异常项与风险等级',
    defaultData: {
      label: '异常检测',
      anomalyDimensions: ['amount', 'frequency'],
    },
  },
  {
    type: 'chart-generate',
    label: '图表生成',
    icon: 'data-line',
    category: 'ai',
    description: '根据数据字段自动生成图表（柱状/折线/饼图/表格）',
    defaultData: {
      label: '图表生成',
      chartType: 'auto',
    },
  },
  {
    type: 'autonomous-agent',
    label: '自主智能体',
    icon: 'magic-stick',
    category: 'ai',
    description: '自主智能体：独立推理、调用工具、可中断等待人工审批',
    defaultData: {
      label: '自主智能体',
      agentTaskPrompt: '{{$input.message}}',
      agentAllowedTools: [],
      agentMaxTurns: 10,
      agentTokenBudget: 100000,
      agentTimeoutSeconds: 300,
      agentInterruptible: false,
      agentInterruptMessage: '智能体需要您的确认',
      agentOutputSource: 'lastMessage',
    },
  },
]

export const AGENT_NODE_COLORS: Record<string, string> = {
  'manual-trigger': '#67C23A',
  'webhook-trigger': '#67C23A',
  'schedule-trigger': '#67C23A',
  'agent-team': '#9B59B6',
  'document-parse': '#409EFF',
  'vision-analyze': '#9B59B6',
  'audio-transcribe': '#67C23A',
  'video-analyze': '#E6A23C',
  'conversation-memory': '#E6A23C',
  'memory-recall': '#E6A23C',
  'memory-write': '#E6A23C',
  'memory-extract': '#00D4FF',
  'handoff': '#9B59B6',
  llm: '#00D4FF',
  'agent-intent': '#9B59B6',
  expert: '#9B59B6',
  tool: '#E6A23C',
  if: '#9B59B6',
  merge: '#409EFF',
  hitl: '#F56C6C',
  end: '#909399',
  'image-generate': '#FF6B35',
  'ppt-generate': '#67C23A',
  'intent-router': '#9B59B6',
  summarizer: '#409EFF',
  'requirement-analyzer': '#409EFF',
  'task-planner': '#409EFF',
  'task-chain': '#E6A23C',
  'collaboration-router': '#9B59B6',
  'agent-loop': '#00D4FF',
  'code-execute': '#607D8B',
  'variable-set': '#795548',
  'switch': '#9B59B6',
  'approval-analyze': '#67C23A',
  'flow-interact': '#409EFF',
  'compliance-check': '#F56C6C',
  'module-assemble': '#9B59B6',
  'form-query': '#00D4FF',
  'anomaly-detect': '#E6A23C',
  'chart-generate': '#909399',
  'autonomous-agent': '#E040FB',
}

export function getPaletteItem(type: AgentNodeType): AgentPaletteItem | undefined {
  const found = AGENT_PALETTE_ITEMS.find((i) => i.type === type)
  if (found) return found
  if (type === 'expert') {
    return {
      type: 'expert',
      label: '插件专家',
      icon: 'cpu',
      category: 'experts',
      description: '从插件中心选择注册专家',
      defaultData: { label: '插件专家' },
    }
  }
  if (type === 'tool') {
    return {
      type: 'tool',
      label: '工具',
      icon: 'set-up',
      category: 'tools',
      description: '从插件中心选择外部工具服务或内置工具',
      defaultData: { label: '工具' },
    }
  }
  return undefined
}
